Remove unuseful npm depdencies
exoplatform/app-center pull request #11
Opened 2020-02-07 14:06 UTC by SaraBoutej

2020-02-07 16:01 UTC, azayati requested changes
See review

2020-02-07 16:01 UTC, azayati commented on app-center-webapps/src/main/webapp/vue-apps/myApplications/components/MyApplications.vue
> +  					<span class="myToolTitle tooltipContent">
</span> missing ?

2020-02-07 16:05 UTC, SaraBoutej commented on app-center-webapps/src/main/webapp/vue-apps/myApplications/components/MyApplications.vue
> +  					<span class="myToolTitle tooltipContent">
no

2020-02-11 10:47 UTC, azayati approved these changes
LGTM

2020-02-11 10:54 UTC, merged