Add app center Drawer style
exoplatform/app-center pull request #5
Opened 2020-01-30 11:42 UTC by SaraBoutej

2020-01-30 13:26 UTC, azayati requested changes
See review

2020-01-30 13:26 UTC, azayati commented on app-center-webapps/src/main/webapp/vue-apps/appLauncher/components/AppLauncher.vue
> +                            <a v-if="index < 9 " target="_blank" :href="application.appUrl">
why index < 9 here ?

2020-01-30 13:26 UTC, azayati commented on app-center-webapps/src/main/webapp/vue-apps/appLauncher/components/AppLauncher.vue
> +                                >View all applications</a>
This label should internationalized

2020-02-03 11:03 UTC, azayati reviewed
See review

2020-02-03 11:03 UTC, azayati commented on app-center-webapps/src/main/webapp/WEB-INF/gatein-resources.xml
> +      <path>/javascript/App-center.js</path>
```suggestion
      <path>/javascript/appCenter.js</path>
```

2020-02-03 11:05 UTC, azayati reviewed
See review

2020-02-03 11:05 UTC, azayati commented on app-center-webapps/src/main/webapp/vue-apps/appLauncher/components/AppLauncher.vue
> +            },
No needed I think

2020-02-03 11:06 UTC, SaraBoutej commented on app-center-webapps/src/main/webapp/WEB-INF/gatein-resources.xml
> +      <path>/javascript/App-center.js</path>
Done!

2020-02-03 11:08 UTC, SaraBoutej commented on app-center-webapps/src/main/webapp/vue-apps/appLauncher/components/AppLauncher.vue
> +            },
Okey

2020-02-03 11:11 UTC, azayati approved these changes
LGTM

2020-02-03 11:12 UTC, merged